### PR TITLE
Add option to include custom RuntimeExceptionHandlerInterceptor, which passes RuntimeException.getMessage to clientlib

### PR DESCRIPTION
**Pull request by erikyangs**
Currently nrtsearch throws:
```
Exception in thread "main" io.grpc.StatusRuntimeException: UNKNOWN
```
This change will make it:
```
Exception in thread "main" io.grpc.StatusRuntimeException: <Grpc Exception Status>: <Exception.getMessage()>
```

Following https://sultanov.dev/blog/exception-handling-in-grpc-java-server/

### CODE REVIEW

**Review by sarthakn7 — COMMENTED** [review]
Can you add a test? You can send a bad search request (e.g. specify non-existent field, set boost to a negative value, etc.) and check that the exception you get in the test has the expected message

**Comment by erikyangs** [comment]
> Can you add a test? You can send a bad search request (e.g. specify non-existent field, set boost to a negative value, etc.) and check that the exception you get in the test has the expected message

@sarthakn7 Currently finding this really hard to test. I can verify the message of the `StatusRuntimeException`, but can't `try/catch` the original `IllegalArgumentException` which makes the build fail.

**Test Code Snippet**
```
  @Rule public ExpectedException thrown = ExpectedException.none();

  @Test
  public void testThrowsRichStatusRuntimeException() {
    thrown.expect(StatusRuntimeException.class);
    thrown.expectMessage(
        "field \"THIS_FIELD_DOES_NOT_EXIST\" is unknown: it was not registered with registerField");
    SearchRequest request =
        SearchRequest.newBuilder()
            .setIndexName(TEST_INDEX)
            .setTopHits(NUM_DOCS)
            .setQuery(getQuery())
            .build();
    // try/catch IllegalArgumentException here doesn't work
    getGrpcServer().getBlockingStub().search(request);
  }
```
**Build snippet**
```
WARNING: error while trying to execute search test_index for index indexName: "test_index"
    topHits: 100
    query {
      termQuery {
        field: "THIS_FIELD_DOES_NOT_EXIST"
        booleanValue: false
      }
    }

    java.lang.IllegalArgumentException: field "THIS_FIELD_DOES_NOT_EXIST" is unknown: it was not registered with registerField
```

**Comment by sarthakn7** [comment]
> > Can you add a test? You can send a bad search request (e.g. specify non-existent field, set boost to a negative value, etc.) and check that the exception you get in the test has the expected message
> 
> @sarthakn7 Currently finding this really hard to test. I can verify the message of the `StatusRuntimeException`, but can't `try/catch` the original `IllegalArgumentException` which makes the build fail.
> 
> **Test Code Snippet**
> 
> ```
>   @Rule public ExpectedException thrown = ExpectedException.none();
> 
>   @Test
>   public void testThrowsRichStatusRuntimeException() {
>     thrown.expect(StatusRuntimeException.class);
>     thrown.expectMessage(
>         "field \"THIS_FIELD_DOES_NOT_EXIST\" is unknown: it was not registered with registerField");
>     SearchRequest request =
>         SearchRequest.newBuilder()
>             .setIndexName(TEST_INDEX)
>             .setTopHits(NUM_DOCS)
>             .setQuery(getQuery())
>             .build();
>     // try/catch IllegalArgumentException here doesn't work
>     getGrpcServer().getBlockingStub().search(request);
>   }
> ```
> 
> **Build snippet**
> 
> ```
> WARNING: error while trying to execute search test_index for index indexName: "test_index"
>     topHits: 100
>     query {
>       termQuery {
>         field: "THIS_FIELD_DOES_NOT_EXIST"
>         booleanValue: false
>       }
>     }
> 
>     java.lang.IllegalArgumentException: field "THIS_FIELD_DOES_NOT_EXIST" is unknown: it was not registered with registerField
> ...
> FAILURE: Build failed with an exception.
> ```

@erikyangs `IllegalArgumentException` is thrown in the server but the client should throw `StatusRuntimeException`. Can you try just catching the generic `Exception` class and see what type of Exception it is?

**Comment by erikyangs** [comment]
@sarthakn7 dug deeper and don't think this PR is needed anymore. Realized the tests were throwing exceptions from a different code path and they already return rich exception messages.

LuceneServer methods add the exception messages: https://sourcegraph.yelpcorp.com/Yelp/nrtsearch@ec29e7c6435c02c09f81985a26730616d49ab037/-/blob/src/main/java/com/yelp/nrtsearch/server/grpc/LuceneServer.java#L808

**Pull request closed without merging**
